// 06_customers_transactions.js
import { v4 as uuidv4 } from "uuid";

export async function seed(knex) {
  await knex("transactions").del();
  await knex("customers").del();

  await knex("customers").insert([
    {
      id: uuidv4(),
      code: "CUST-BUDI001",
      name: "Budi Santoso",
      phone: "081234567890",
      email: "budi@email.com",
      total_spend: 0,
      status: "active",
      address: "Jl. Merdeka No. 10",
      city: "Jakarta Pusat",
      region: "DKI Jakarta",
      subregion: "Gambir",
      customer_group: "General",
      created_at: new Date(),
    },
    {
      id: uuidv4(),
      code: "CUST-SITI002",
      name: "Siti Aminah",
      phone: "082345678901",
      email: "siti@email.com",
      total_spend: 0,
      status: "active",
      address: "Jl. Diponegoro No. 25",
      city: "Bandung",
      region: "Jawa Barat",
      subregion: "Coblong",
      customer_group: "Member",
      created_at: new Date(),
    },
    {
      id: uuidv4(),
      code: "CUST-AGUS003",
      name: "Agus Wijaya",
      phone: "083456789012",
      email: null,
      total_spend: 0,
      status: "active",
      address: "Perumahan Griya Asri Blok A3",
      city: "Surabaya",
      region: "Jawa Timur",
      subregion: "Wonokromo",
      customer_group: "General",
      created_at: new Date(),
    },
    {
      id: uuidv4(),
      code: "CUST-DEWI004",
      name: "Dewi Kusuma",
      phone: "084567890123",
      email: "dewi@email.com",
      total_spend: 0,
      status: "active",
      address: "Jl. Veteran No. 88",
      city: "Yogyakarta",
      region: "DI Yogyakarta",
      subregion: "Gondokusuman",
      customer_group: "Member",
      created_at: new Date(),
    },
    {
      id: uuidv4(),
      code: "CUST-RUDI005",
      name: "Rudi Hermawan",
      phone: null,
      email: null,
      total_spend: 0,
      status: "inactive",
      address: null,
      city: null,
      region: null,
      subregion: null,
      customer_group: "General",
      created_at: new Date(),
    },
  ]);
}
