// 09_transactions.js
import { v4 as uuidv4 } from 'uuid';

export async function seed(knex) {
  await knex('transaction_promotions').del();
  await knex('transaction_item_promotions').del();
  await knex('transaction_items').del();
  await knex('transactions').del();

  const customers = await knex('customers').select('id', 'name');
  const getCustomerId = name => customers.find(c => c.name === name)?.id;

  await knex('transactions').insert([
    {
      id: uuidv4(),
      invoice_number: 'INV-20260701-001',
      customer_id: getCustomerId('Budi Santoso'),
      status: 'completed',
      subtotal: 13000,
      total_discount: 1300,
      grand_total: 11700,
      paid_amount: 11700,
      change_amount: 0,
      payment_method: 'cash',
      transacted_at: new Date('2026-07-01T10:30:00'),
      created_at: new Date('2026-07-01T10:30:00'),
      payment_status: 'paid',
      paid_at: new Date('2026-07-01T10:30:00'),
      midtrans_order_id: null,
      midtrans_token: null,
      midtrans_pdf_url: null,
      delivery_address: null,
      delivery_city: null,
      delivery_region: null,
      delivery_subregion: null,
      delivery_note: null,
    },
    {
      id: uuidv4(),
      invoice_number: 'INV-20260701-002',
      customer_id: getCustomerId('Siti Aminah'),
      status: 'completed',
      subtotal: 41500,
      total_discount: 0,
      grand_total: 41500,
      paid_amount: 50000,
      change_amount: 8500,
      payment_method: 'qris',
      transacted_at: new Date('2026-07-01T11:15:00'),
      created_at: new Date('2026-07-01T11:15:00'),
      payment_status: 'paid',
      paid_at: new Date('2026-07-01T11:15:00'),
      midtrans_order_id: 'MID-20260701-002',
      midtrans_token: 'snap-token-002',
      midtrans_pdf_url: null,
      delivery_address: null,
      delivery_city: null,
      delivery_region: null,
      delivery_subregion: null,
      delivery_note: null,
    },
    {
      id: uuidv4(),
      invoice_number: 'INV-20260701-003',
      customer_id: null,
      status: 'completed',
      subtotal: 14000,
      total_discount: 0,
      grand_total: 14000,
      paid_amount: 15000,
      change_amount: 1000,
      payment_method: 'cash',
      transacted_at: new Date('2026-07-01T14:20:00'),
      created_at: new Date('2026-07-01T14:20:00'),
      payment_status: 'paid',
      paid_at: new Date('2026-07-01T14:20:00'),
      midtrans_order_id: null,
      midtrans_token: null,
      midtrans_pdf_url: null,
      delivery_address: null,
      delivery_city: null,
      delivery_region: null,
      delivery_subregion: null,
      delivery_note: null,
    },
    {
      id: uuidv4(),
      invoice_number: 'INV-20260702-001',
      customer_id: getCustomerId('Agus Wijaya'),
      status: 'pending',
      subtotal: 332000,
      total_discount: 33200,
      grand_total: 298800,
      paid_amount: 0,
      change_amount: 0,
      payment_method: null,
      transacted_at: new Date('2026-07-02T09:00:00'),
      created_at: new Date('2026-07-02T09:00:00'),
      payment_status: 'pending',
      paid_at: null,
      midtrans_order_id: 'MID-20260702-001',
      midtrans_token: 'snap-token-001',
      midtrans_pdf_url: 'https://midtrans.com/pdf/MID-20260702-001',
      delivery_address: 'Jl. Sudirman No. 123',
      delivery_city: 'Jakarta Selatan',
      delivery_region: 'DKI Jakarta',
      delivery_subregion: 'Kebayoran Baru',
      delivery_note: 'Ditinggal di depan pintu',
    },
    {
      id: uuidv4(),
      invoice_number: 'INV-20260702-002',
      customer_id: getCustomerId('Dewi Kusuma'),
      status: 'cancelled',
      subtotal: 22000,
      total_discount: 0,
      grand_total: 22000,
      paid_amount: 0,
      change_amount: 0,
      payment_method: null,
      transacted_at: new Date('2026-07-02T16:45:00'),
      created_at: new Date('2026-07-02T16:45:00'),
      payment_status: 'cancelled',
      paid_at: null,
      midtrans_order_id: null,
      midtrans_token: null,
      midtrans_pdf_url: null,
      delivery_address: null,
      delivery_city: null,
      delivery_region: null,
      delivery_subregion: null,
      delivery_note: null,
    },
  ]);
}